### PR TITLE
fix for #52 - remove websocket-polyfill

### PR DESCRIPTION
**Pull request by jeremyd**
removes websocket-polyfill
adds pnpm to dev dependencies - build required it

### CODE REVIEW

**Comment by jeremyd** [comment]
sorry, this doesn't quite do it, gotta remove more refs to polyfill..

**Comment by bijeebuss** [comment]
good-luck

**Comment by jeremyd** [comment]
Ok, this is ready.  Thanks for the reminder @bijeebuss :)

the pnpm-lock.json has been modified to also remove the polyfill

**Comment by jeremyd** [comment]
and by ready, i mean ready for review.  I'm actually not quite sure if pnpm-lock.json should be in the repo at all, and my file has a lot of diffs (for linux).  Any opinions on this from the maintainers?

**Comment by pablof7z** [comment]
is the addition of the utf8 dependency really necessary? I'm not sure why it's there 🤔

**Comment by jeremyd** [comment]
> is the addition of the utf8 dependency really necessary? I'm not sure why it's there 🤔

it was already there, this change just removes the comma from the last line of the json..

**Comment by pablof7z** [comment]
> > is the addition of the utf8 dependency really necessary? I'm not sure why it's there 🤔
> 
> it was already there, this change just removes the comma from the last line of the json..

🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

thanks 😅

**Review by pablof7z — APPROVED** [review]

**Pull request merged**
