### PR TITLE
Adds `devcontainer` 

### PR DESCRIPTION
**Pull request by anon-dev-gh**
A first step to support [`devcontainers`](https://containers.dev/) and provide reproducible development experiences to ease onboarding of new developers.

Tested as 

```javascript
> const { default: NDK } = require('./ndk');
undefined
> const ndk = new NDK({"explicitRelayUrls": ["wss://a.relay", "wss:another.relay"]})
```

after 

```
root@dadae588358b:/workspaces/ndk# node
``` 

in the container itself.

Disclaimer: I'm by no means a javascript expert, this is what I've come up with after some hacking and I'm sure many improvements can be made over the `Dockerfile` and whatnot.

### CODE REVIEW

**Comment by erskingardner** [comment]
@anon-dev-gh I'm going to close this as it's hugely out of date. Feel free to reopen if you still think this should be considered.

**Comment by anon-dev-gh** [comment]
> @anon-dev-gh I'm going to close this as it's hugely out of date. Feel free to reopen if you still think this should be considered.

Yes, I still think there is a point on having `devcontainer`

What specifically do you consider out of the date? my fork branch? Then, after rebasing could this PR still be considered?

**Comment by erskingardner** [comment]
Ok – happy to hear more. TBH, I've not used devcontainers before. I noticed some ##FIXME comments in the code, does the container work right now as the PR currently stands? Or is there more that needs to be done?

**Comment by anon-dev-gh** [comment]
Is just a draft on an early version of devcontainer support. They are great for onboarding.

My background comes from -not node- backend so I don't have a local setup with `node` or anything else. This `devcontainer` would allow me to spawn a vscode instance and be able to contribute right away, without the hassle of having to install node locally.

Also, the `devcontainer` should be considered as incremental, project relevant customizations such as plugins, out of the box testing support and so on are of great value and can be added as later iterations

This is just a first step.

Regarding `FIXME` are related to the above statement, not sure which `node` version(s) should we support, path inside the container and some decisions have been made in a rather arbitrary way just to have a first alpha version.

I've made some updates to the `devcontainer`, and the feedback is even better because the command I've used to test it fails reporting a relay url error

```shell
> const { default: NDK } = require('./ndk');
undefined
> const ndk = new NDK({"explicitRelayUrls": ["wss://a.relay", "wss:another.relay"]})
Uncaught TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at normalizeURL (/workspaces/ndk/node_modules/.pnpm/nostr-tools@2.4.0_typescript@5.2.2/node_modules/nostr-tools/lib/cjs/relay.js:74:11)
    at new AbstractRelay (/workspaces/ndk/node_modules/.pnpm/nostr-tools@2.4.0_typescript@5.2.2/node_modules/nostr-tools/lib/cjs/relay.js:296:16)
    at new Relay (/workspaces/ndk/node_modules/.pnpm/nostr-tools@2.4.0_typescript@5.2.2/node_modules/nostr-tools/lib/cjs/relay.js:567:5)
    at new NDKRelayConnectivity (/workspaces/ndk/ndk/dist/index.js:236:18)
    at new NDKRelay (/workspaces/ndk/ndk/dist/index.js:1177:25)
    at new NDKPool (/workspaces/ndk/ndk/dist/index.js:6476:21)
    at new NDK (/workspaces/ndk/ndk/dist/index.js:7070:17) {
  code: 'ERR_INVALID_URL',
  input: 'wss://wss:another.relay/'
```

**Review by erskingardner — APPROVED** [review]

**Comment by erskingardner** [comment]
@anon-dev-gh if this works ok, I'm happy to merge.

**Review by erskingardner — APPROVED** [review]

**Pull request merged**
