### PR TITLE
Move event validation and signature verification in-house

### PR DESCRIPTION
**Pull request by erskingardner**
Since there are going to be a bunch of different things we need to do to remove nostr-tools I'm making a branch called `remove-nostr-tools` and then merging these smaller PRs to that branch so that we can keep track of things easier.

### CODE REVIEW

**Comment by pablof7z** [comment]
This never works and just adds extra work; let's just merge into master all small PRs. Integration branches are a shitcoin 😅

**Comment by erskingardner** [comment]
Base branch changed.

**Comment by verbiricha** [comment]
> merging these smaller PRs to that branch so that we can keep track of things easier.

Atomic commits that can be reviewed one by one in a single PR is best imo, more PRs adds a lot of overhead.

Commenting because I want this

**Comment by erskingardner** [comment]
> > merging these smaller PRs to that branch so that we can keep track of things easier.
> 
> Atomic commits that can be reviewed one by one in a single PR is best imo, more PRs adds a lot of overhead.
> 
> Commenting because I want this

@verbiricha I'm unclear, you'd prefer the method I originally suggested or you think @pablof7z's small atomic PRs commited to master is better/easier.

**Comment by pablof7z** [comment]
> > merging these smaller PRs to that branch so that we can keep track of things easier.
> 
> Atomic commits that can be reviewed one by one in a single PR is best imo, more PRs adds a lot of overhead.
> 

integration branches always end up with a fuckload of unnecessary conflicts and are harder to reason around. Every single time I've done integration branches I've massively regretted it.

The only reason to use integration branches imo is if the overhead of doing non-breaking PRs is way larger than the aggregate overhead of breaking PRs.

**Review by pablof7z — APPROVED** [review]
LFGTM

**Pull request merged**
