### PR TITLE
Remove hexpubkey references everywhere

### PR DESCRIPTION
**Pull request by erskingardner**
And adding a few missing function return signatures.

### CODE REVIEW

**Comment by pablof7z** [comment]
Is this also deprecating it from `getUser`, etc? We should 😀

**Comment by erskingardner** [comment]
I left it there for now. Just focused on removing NDK's uses of it. I think we need to make sure that we remove it from `getUser` with a bit more warning.

**Comment by pablof7z** [comment]
It's been marked as deprecated for quite a while 😅 but ok, we can keep it for a bit longer

**Review by pablof7z — APPROVED** [review]

**Comment by erskingardner** [comment]
Next release let's make a point in the changelog that the next major (v3) will remove support for `hexpubkey` entirely.

**Pull request merged**
